### ISSUE TITLE
hasBeenActive should be false to the first element

### ISSUE THREAD

**Issue by xDae** [Jibbedi/react-wizard-primitive#21]
I think  the `hasBeenActive` should be false in the first render to the first element, if you want to know if is active you can use `isActive`

for me `hasBeenActive` active is when you has pass that level

**Comment by Jibbedi** [comment]
Hi!
Thanks for reaching out and sorry for taking so long to respond.

I see your point. It's probably a poor naming on my part and should have been called `visited` or something.
I was actually thinking about doing it the way you suggested when I implemented it.

However, my use case at the time was that I needed to know whether the step was visited or is currently active that's why I decided to merge those two states together.

I figured it would be sufficient to be able to check if a step `hasBeenActive && !isActive` to support all kinds of use cases.

Do you have a use case where you need to know whether a step is visited for the first time? If so, we can probably figure something out :-)
